### ISSUE TITLE
Subtitles?

### ISSUE THREAD

**Issue by NeverEatYellowSwissSnow** [ManBehindMooN/kodi_plugin_video_srgssr_ch_replay#4]
Thanks for the app which works great. Only thing I am missing are subtitles.
For example: If I watch a program from the RTR website directly with a browser, I can activate german subtitles.
Within the Kodi app I have not found any possibilities to do so.
Is this not possible (yet)? If not, are there any plans to implement such a feature in the future?
Thank you in advance!

**Comment by ManBehindMooN** [comment]
@NeverEatYellowSwissSnow Thank you for your feedback. There is an official API for subtitles https://developer.srgssr.ch/apis/srgssr-play-subtitles/docs. We will have a look at it and check it out if there is a way to bring subtitles to the add-on.

**Comment by ManBehindMooN** [comment]
@meierfra & @NeverEatYellowSwissSnow: branch has been created https://github.com/ManBehindMooN/kodi_plugin_video_srgssr_ch_replay/tree/feature/issue_4_add_subtitles. There might be a real chance to make it work. See TODOs in Python code: https://github.com/ManBehindMooN/kodi_plugin_video_srgssr_ch_replay/blob/feature/issue_4_add_subtitles/plugin.video.srgssr_ch_replay/addon.py.

**Comment by ManBehindMooN** [comment]
@meierfra & @NeverEatYellowSwissSnow: FYI the skeleton code to add subtitles to the stream has been created on the branch and it works just fine with Kodi. The only thing left is to retrieve the subtitles from the SRG SSR API.

**Comment by ManBehindMooN** [comment]
An issue has been opened over the SRG SSR API portal. Waiting for a response...

**Comment by ManBehindMooN** [comment]
We got a response from the SRG SSR group. This part of the issue is solved.

**Comment by ManBehindMooN** [comment]
@meierfra & @NeverEatYellowSwissSnow: The official subtitle API has been implemented (not finally yet; see TODOs). The subtitles can be loaded but it is still shaky. Have a look at it if you are interested.

**Comment by NeverEatYellowSwissSnow** [comment]
That's pretty neat! But I think I'll wait until you are going to release it unless you need a beta tester ;-)

**Comment by ManBehindMooN** [comment]
@meierfra Ready to release? Have a look the implementation and documentation and give a feedback, please. Cheers!

**Comment by ManBehindMooN** [comment]
Pull request has been created: https://github.com/xbmc/repo-plugins/pull/3875. This is a partial delivery as the ttml subtitle format is not supported yet. The new version should be available in the repository in the next few days.
@NeverEatYellowSwissSnow: If you have any issues, let us know. We will only support the ttml subtitle format if anybody requests it.

**Comment by NeverEatYellowSwissSnow** [comment]
> Pull request has been created: [xbmc/repo-plugins#3875](https://github.com/xbmc/repo-plugins/pull/3875). This is a partial delivery as the ttml subtitle format is not supported yet. The new version should be available in the repository in the next few days. @NeverEatYellowSwissSnow: If you have any issues, let us know. We will only support the ttml subtitle format if anybody requests it.

That's pretty neat, thank you a thousand times mate!

**Comment by ManBehindMooN** [comment]
I tested it and it works. But the 3.0.2 version is needed and the PR https://github.com/xbmc/repo-plugins/pull/3875 was merged 2 hours ago and therefore I expect it to be in the official repo between 24h to 48h from now. If you have the accurate version then you need to enable the subtitles in the settings and add the sufficient subtitle consumer key & secret. Please refer the https://github.com/ManBehindMooN/kodi_plugin_video_srgssr_ch_replay/blob/master/README.md. If you have any further questions (also when it works ;), let us know.

**Comment by ManBehindMooN** [comment]
@Grandma-Betty 3.0.2 is live and can be downloaded through the official repo in your Kodi. Go for it 🦄

**Comment by ManBehindMooN** [comment]
@Grandma-Betty does it work?

**Comment by Grandma-Betty** [comment]
I can confirm it works flawlessly. What a much better experience now!
Keep your work like this mate, your app is unbeatable.
Thanks a bunch man! You're my hero for today!
