### ISSUE TITLE
Discover tv shows

### ISSUE THREAD

**Issue by lackyluuk** [ManBehindMooN/kodi_plugin_video_srgssr_ch_replay#6]
Hi.
First of all, thank you for this wonderful add-on. I really appreciate your work and enjoy using it :)
I would like to ask for a new way to discover tv shows. I would love to browse through all available tv shows (like browsing in Netflix or Disney+) without choosing first the beginning letter of the tv shows.
There are a lot unknown tv shows which I do not discover unless I go through the whole list of all the letters (1. letter of the tv show)
Thank you & keep on your wonderful work :))

**Comment by ManBehindMooN** [comment]
Hi @lackyluuk,

Personally, I'm not really a big fan of this feature but it's not a problem. I introduced an experimental section in the settings. Have a look at https://github.com/ManBehindMooN/kodi_plugin_video_srgssr_ch_replay/pull/5/. I don't know yet when we gonna release the next version but you can already try it out and install it manually. If you do, please give us a feedback.

**Comment by lackyluuk** [comment]
That was fast. I will test this branch and give you feedback asap. Thank you!

**Comment by ManBehindMooN** [comment]
You're welcome. The code is quite nicely structured and it only took a couple of minutes. Testing takes most of the time. I did a fast regression testing and so no major bugs should show up. Thank you and happy testing!

**Comment by lackyluuk** [comment]
I did some testing and I could not find any issues. All works perfectly :) . As you said, it takes some time to load all shows but it's acceptable (Pi4, 2 and 4 gb ram).
I have two more questions:
- Does SRF provide the show type (genre) like drama, talk show, etc.? If yes, this could also be another way of sorting the shows.
- All tv shows provide a thumbnail picture when scrolling through the list. Is it possible to have this for the channel itself as well (SRF, SRF Info, RTS, etc.)? There I on)ly see a folder icon. 

Thank you :)

**Comment by lackyluuk** [comment]
Cool, this sounds promising :) Thanks for your work.
Feel free to close this issue since my initial point is already implemented.

Best regards

**Comment by ManBehindMooN** [comment]
@lackyluuk https://github.com/xbmc/repo-plugins/pull/3921 has been created. Within the next couple of days (up to 4 weeks) it should be in the official Kodi repo. I will close the issue after the merge.

**Comment by ManBehindMooN** [comment]
@lackyluuk with the new PR https://github.com/ManBehindMooN/kodi_plugin_video_srgssr_ch_replay/pull/15 or next version 3.0.4 thumbnail picture for channels (business units) have been added.
